[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"

# RPC endpoints for different networks
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"

# Etherscan API keys for contract verification
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
base_sepolia = { key = "${ETHERSCAN_API_KEY}" }
mumbai = { key = "${ETHERSCAN_API_KEY}" }
